### ISSUE TITLE
LuaFrontend v1.15 Negatively Effects Growth Abilities for KH2FM Epic Games Version

### ISSUE THREAD

**Issue by PowerStallion** [TopazTK/LuaFrontend#3]
When running the Software/Program itself, Sora is not able to gain any of the growth abilities (High Jump, Quick Run) from his drive forms. It has nothing to do with the lua mod files

**Comment by TopazTK** [comment]
Literally impossible if there are not any Lua files. LuaFrontend does no operations when it does not have any scripts loaded.
Closing.

**Comment by PowerStallion** [comment]
This is with and without the LUA Mod files. For some reason when I play the game without running LuaFrontend, I was able to get the Growth abilities normally. I don't know what else to tell you
